name: Deploy Nuxt 4 to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build Application
        run: bun run generate
        env:
          NUXT_PUBLIC_WORDPRESS_URL: ${{ secrets.NUXT_PUBLIC_WORDPRESS_URL }}
          NUXT_PUBLIC_GA_MEASUREMENT_ID: ${{ secrets.NUXT_PUBLIC_GA_MEASUREMENT_ID }}
          NUXT_PUBLIC_GTAG_ID: ${{ secrets.NUXT_PUBLIC_GTAG_ID }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: '.output/public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5